name: YouTube Beam Pipeline

on:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests pynacl flask apache-beam[gcp] google-auth google-cloud-firestore google-cloud-storage

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
            credentials_json: ${{ secrets.GCP_SECRET_KEY }}

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Run Beam pipeline
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URIS: ${{ secrets.REDIRECT_URIS }}
          TOKEN_URI: ${{ secrets.TOKEN_URI }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          python backend/pipelines/run_all_users.py
